### ISSUE TITLE
Unable to load Fog::Packet::Compute

### ISSUE THREAD

**Issue by derks** [jeefy/vagrant-packet#5]
Unable to use Vagrant Packet after latest upgrade.

- Vagrant: 2.1.5
- Packet Plugin: 0.1.6

```
$ vagrant status
[fog][DEPRECATION] Unable to load Fog::Packet::Compute
[fog][DEPRECATION] The format Fog::Compute::Packet is deprecated
/Users/derks/.vagrant.d/gems/2.4.4/gems/fog-packet-1.0.1/lib/fog/compute/packet/compute.rb:290:in `request': 404 {"errors"=>["Not found"]} (RuntimeError)
	from /Users/derks/.vagrant.d/gems/2.4.4/gems/fog-packet-1.0.1/lib/fog/compute/packet/requests/get_device.rb:7:in `get_device'
	from /Users/derks/.vagrant.d/gems/2.4.4/gems/fog-packet-1.0.1/lib/fog/compute/packet/models/devices.rb:16:in `get'
	from /Users/derks/.vagrant.d/gems/2.4.4/gems/vagrant-packet-0.1.6/lib/vagrant-packet/action/read_state.rb:26:in `read_state'
	from /Users/derks/.vagrant.d/gems/2.4.4/gems/vagrant-packet-0.1.6/lib/vagrant-packet/action/read_state.rb:17:in `call'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/derks/.vagrant.d/gems/2.4.4/gems/vagrant-packet-0.1.6/lib/vagrant-packet/action/connect_packet.rb:24:in `call'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:239:in `action_raw'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:208:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:190:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:194:in `action'
	from /Users/derks/.vagrant.d/gems/2.4.4/gems/vagrant-packet-0.1.6/lib/vagrant-packet/provider.rb:34:in `state'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:526:in `state'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:146:in `initialize'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:716:in `machine'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/v2/command.rb:213:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/v2/command.rb:212:in `map'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/v2/command.rb:212:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/status/command.rb:20:in `execute'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/bin/vagrant:164:in `<main>'
```

**Comment by jeefy** [comment]
Are you able to upgrade your version of Vagrant?

I just verified it working on my laptop using Vagrant 2.2.0.

**Comment by derks** [comment]
Not sure what changed or where, but on 2.1.5 I'm no longer seeing that warning/error.  Thanks.
